Repository sigmf/sigmf-python, pull requests merged in 2025-01, with the labels that each got.

#98 Add __eq__ method to SigMFFile
  sigmf/sigmffile.py
  tests/test_sigmffile.py
Labels: enhancement

#97 feature/readthedocs
  .github/workflows/main.yml
  .gitignore
  .readthedocs.yaml
  README.md
  docs/Makefile
  docs/make.bat
  docs/requirements.txt
  docs/source/_templates/custom-class-template.rst
  docs/source/_templates/custom-module-template.rst
  docs/source/advanced.rst
  docs/source/api.rst
  docs/source/conf.py
  docs/source/developers.rst
  docs/source/faq.rst
  docs/source/index.rst
  docs/source/quickstart.rst
  pyproject.toml
  sigmf/__init__.py
Labels: documentation

#101 cross-platform worker estimation
  sigmf/validate.py
Labels: bug

#94 os.path converted pathlib.Path
  sigmf/apps/convert_wav.py
  sigmf/archive.py
  sigmf/archivereader.py
  sigmf/schema.py
  sigmf/sigmf_hash.py
  sigmf/sigmffile.py
  sigmf/utils.py
  tests/test_archive.py
  tests/test_archivereader.py
  tests/test_ncd.py
  tests/test_sigmffile.py
Labels: enhancement
